#!/usr/bin/env swift

import Foundation

let root = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .deletingLastPathComponent()

let inputs: [(name: String, path: String)] = [
    ("verifier", "Verifier/LicenseVerifier.swift"),
    ("licenseConfig", "Templates/Swift/LicenseConfig.swift.template"),
    ("licenseManager", "Templates/Swift/LicenseManager.swift.template"),
    ("activationView", "Templates/Swift/LicenseActivationView.swift.template"),
    ("integrationGuide", "Templates/Swift/LICENSE_INTEGRATION.md.template"),
]

func expression(for data: Data) -> String {
    let encoded = data.base64EncodedString()
    let chunks = stride(from: 0, to: encoded.count, by: 100).map { offset -> String in
        let start = encoded.index(encoded.startIndex, offsetBy: offset)
        let end = encoded.index(start, offsetBy: min(100, encoded.distance(from: start, to: encoded.endIndex)))
        return "\"\(encoded[start..<end])\""
    }
    return chunks.joined(separator: " +\n            ")
}

var output = """
// Generated by Tools/embed-templates.swift. Do not edit by hand.

import Foundation

enum EmbeddedTemplates {
    private static func decode(_ value: String) -> String {
        guard let data = Data(base64Encoded: value),
              let text = String(data: data, encoding: .utf8) else {
            preconditionFailure("corrupt embedded integration template")
        }
        return text
    }

"""

for input in inputs {
    let data = try Data(contentsOf: root.appendingPathComponent(input.path))
    output += "    static let \(input.name) = decode(\n            \(expression(for: data)))\n\n"
}
output += "}\n"

let destination = root.appendingPathComponent("Sources/CLI/EmbeddedTemplates.swift")
try output.write(to: destination, atomically: true, encoding: .utf8)
